### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by silente** [DebiprasadXD/link-media-scraper-bot#11]
Traceback (most recent call last):
  File "bot.py", line 17, in <module>
    app = session.session_gen.gen_session()
  File "/home/tbot/session/session_gen.py", line 10, in gen_session
    with app:
  File "/home/tbot/lib/python3.8/site-packages/pyrogram/client.py", line 280, in __enter__
    return self.start()
  File "/home/tbot/lib/python3.8/site-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/tbot/lib/python3.8/site-packages/pyrogram/methods/utilities/start.py", line 58, in start
    is_authorized = await self.connect()
  File "/home/tbot/lib/python3.8/site-packages/pyrogram/methods/auth/connect.py", line 40, in connect
    await self.load_session()
  File "/home/tbot/lib/python3.8/site-packages/pyrogram/client.py", line 563, in load_session
    await self.storage.open()
  File "/home/tbot/lib/python3.8/site-packages/pyrogram/storage/file_storage.py", line 63, in open
    self.update()
  File "/home/tbot/lib/python3.8/site-packages/pyrogram/storage/file_storage.py", line 52, in update
    self.version(version)
  File "/home/tbot/lib/python3.8/site-packages/pyrogram/storage/sqlite_storage.py", line 224, in version
    self.conn.execute(
sqlite3.OperationalError: database is locked

**Comment by debiplobi** [comment]
steps to reproduce ?

**Comment by silente** [comment]
Immediately when I run the bot.py script

I take the opportunity to ask, how to configure a proxy that requires authentication.

**Comment by debiplobi** [comment]
> Immediately when I run the bot.py script
> 
> I take the opportunity to ask, how to configure a proxy that requires authentication.

strange, not happening with me, be sure to fill correct required fields in example.env file
proxy with authentication isn't supported, you can use webshare.io proxies, although you won't need one if you are from India, can't tell for other countries but mostly works.

**Comment by silente** [comment]
I delete the file "session" inside my folder for solve the problem.
