### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by silente** [DebiprasadXD/link-media-scraper-bot#12]
How to reproduce the problem:

I start my bot with /start and i paste /bunkr https://cdn10.bunkr.ru/clipart3265712-jK0fpMZR.png

python3 bot.py
https://cdn10.bunkr.ru/clipart3265712-jK0fpMZR.png
https://cdn10.bunkr.ru/clipart3265712-jK0fpMZR.png
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/tbot/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "bot.py", line 48, in send_bunkrmedia
    handlers.bunkr.exec_bunkr(client, message)
  File "/home/tbot/handlers/bunkr.py", line 27, in exec_bunkr
    url_list = helpers.bunkr_scraper.bunkr_scraper(text)
  File "/home/tbot/helpers/bunkr_scraper.py", line 19, in bunkr_scraper
    for i in script:
TypeError: 'NoneType' object is not iterable

**Comment by debiplobi** [comment]
I have fixed bunkr scraper you can try it...but it only works for album/folders not for individual links.
