### ISSUE TITLE
bunkr handler is currently broken for heroku

### ISSUE THREAD

**Issue by debiplobi** [DebiprasadXD/link-media-scraper-bot#2]

**Comment by N30Z3N** [comment]
this is log btw 

`2022-04-09T17:31:17.467083+00:00 app[worker.1]: Response FAIL: 403

2022-04-09T17:31:17.467085+00:00 app[worker.1]: Traceback (most recent call last):

2022-04-09T17:31:17.467086+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 224, in handler_worker

2022-04-09T17:31:17.467086+00:00 app[worker.1]:     await self.loop.run_in_executor(

2022-04-09T17:31:17.467087+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/concurrent/futures/thread.py", line 58, in run

2022-04-09T17:31:17.467087+00:00 app[worker.1]:     result = self.fn(*self.args, **self.kwargs)

2022-04-09T17:31:17.467088+00:00 app[worker.1]:   File "/app/bot.py", line 48, in send_bunkrmedia

2022-04-09T17:31:17.467088+00:00 app[worker.1]:     handlers.bunkr.exec_bunkr(client, message)

2022-04-09T17:31:17.467088+00:00 app[worker.1]:   File "/app/handlers/bunkr.py", line 19, in exec_bunkr

2022-04-09T17:31:17.467089+00:00 app[worker.1]:     url_list = helpers.grabber.get_urls(text)

2022-04-09T17:31:17.467089+00:00 app[worker.1]:   File "/app/helpers/grabber.py", line 16, in get_urls

2022-04-09T17:31:17.467089+00:00 app[worker.1]:     links = linkGrabber.Links(user_link)

2022-04-09T17:31:17.467090+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/linkGrabber/__init__.py", line 32, in __init__

2022-04-09T17:31:17.467090+00:00 app[worker.1]:     raise ValueError('Response FAIL: %s' %

2022-04-09T17:31:17.467090+00:00 app[worker.1]: ValueError: Response FAIL: 403`

**Comment by debiplobi** [comment]
> this is log btw
> 
> `2022-04-09T17:31:17.467083+00:00 app[worker.1]: Response FAIL: 403
> 
> 2022-04-09T17:31:17.467085+00:00 app[worker.1]: Traceback (most recent call last):
> 
> 2022-04-09T17:31:17.467086+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 224, in handler_worker
> 
> 2022-04-09T17:31:17.467086+00:00 app[worker.1]: await self.loop.run_in_executor(
> 
> 2022-04-09T17:31:17.467087+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.10/concurrent/futures/thread.py", line 58, in run
> 
> 2022-04-09T17:31:17.467087+00:00 app[worker.1]: result = self.fn(*self.args, **self.kwargs)
> 
> 2022-04-09T17:31:17.467088+00:00 app[worker.1]: File "/app/bot.py", line 48, in send_bunkrmedia
> 
> 2022-04-09T17:31:17.467088+00:00 app[worker.1]: handlers.bunkr.exec_bunkr(client, message)
> 
> 2022-04-09T17:31:17.467088+00:00 app[worker.1]: File "/app/handlers/bunkr.py", line 19, in exec_bunkr
> 
> 2022-04-09T17:31:17.467089+00:00 app[worker.1]: url_list = helpers.grabber.get_urls(text)
> 
> 2022-04-09T17:31:17.467089+00:00 app[worker.1]: File "/app/helpers/grabber.py", line 16, in get_urls
> 
> 2022-04-09T17:31:17.467089+00:00 app[worker.1]: links = linkGrabber.Links(user_link)
> 
> 2022-04-09T17:31:17.467090+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.10/site-packages/linkGrabber/**init**.py", line 32, in **init**
> 
> 2022-04-09T17:31:17.467090+00:00 app[worker.1]: raise ValueError('Response FAIL: %s' %
> 
> 2022-04-09T17:31:17.467090+00:00 app[worker.1]: ValueError: Response FAIL: 403`

yes I knew it , I'm trying to find a workaround to fix this.

**Comment by debiplobi** [comment]
Okay, it has been fixed you can use proxy if bunkr handler gives any forbidden(403) error.
