### ISSUE TITLE
API_ID not found. Declare it as envvar or define a default value.

### ISSUE THREAD

**Issue by needsupport** [DebiprasadXD/link-media-scraper-bot#6]
MacBook-Pro link-media-scraper-bot % python3 bot.py
Traceback (most recent call last):
  File "/Users/**/Desktop/LM/link-media-scraper-bot/bot.py", line 6, in <module>
    import session.session_gen
  File "/Users/**Desktop/LM/link-media-scraper-bot/session/session_gen.py", line 4, in <module>
    api_id = config("API_ID")
  File "/opt/homebrew/lib/python3.10/site-packages/decouple.py", line 243, in __call__
    return self.config(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/decouple.py", line 105, in __call__
    return self.get(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/decouple.py", line 90, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: API_ID not found. Declare it as envvar or define a default value.

can you help me understand where I am going wrong. Thanks

**Comment by debiplobi** [comment]
Read the environment variable section of readme,
You haven't declared API_ID in .env file
